# Generated by Django 5.1 on 2024-08-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.CharField(max_length=10, verbose_name='Data de nascimento')),
                ('valor', models.FloatField()),
                ('ativo', models.BooleanField()),
            ],
        ),
    ]
